--------------------------------------
--Explore All Objects in the Database
--------------------------------------

SELECT * FROM INFORMATION_SCHEMA.TABLES


-- Explore All the Columns in the Database

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_products'

--------------------------------------
--Dimensions Exploration
--------------------------------------

--Explore All Countries our customera come from

SELECT DISTINCT country FROM gold.dim_customers

--Explore All Categories "The Major Divisions"

SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1,2,3

--------------------------------------
--Date Exploration
--------------------------------------

--Find the date of first and last order
--How many years of sales are available

SELECT 
MIN(order_date) AS first_order_date,
MAX(order_date) AS last_order_date,
DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_years --checking data availability period
FROM gold.fact_sales

--Find Youngest & Oldest customer

SELECT 
MIN(birthdate) AS oldest_birthdate,
DATEDIFF(year,MIN(birthdate),GETDATE())  AS oldest_age,
MAX(birthdate) AS youngest_age,
DATEDIFF(year,MAX(birthdate),GETDATE()) AS youngest_age
FROM GOLD.dim_customers

--------------------------------------
--Measures Exploration
--------------------------------------

--Fact Sales

SELECT

SUM(sales_amount) AS total_sales,							--Find the Total Sales
SUM(quantity) AS total_item_sold,							--How many items are sold
AVG(price) AS avg_selling_price,							-- Average Selling Price
COUNT(DISTINCT order_number) AS total_orders,				--Total number of orders
COUNT(DISTINCT customer_key) AS customers_placed_order		--How many customers have placed order

FROM gold.fact_sales

--Dim Products

SELECT

COUNT(product_name) AS total_products		--Count total products

FROM gold.dim_products

--Dim Customers

SELECT
COUNT(customer_id) AS total_customer		--total numbers of customers
FROM gold.dim_customers

--------------------------------------------------------------
--Generate a report that shows all key metrics of the business
--------------------------------------------------------------

SELECT 
'Total Sales' AS Measures, SUM(sales_amount) AS Measure_Value
FROM gold.fact_sales

UNION ALL

SELECT 
'Total Quantity' AS Measures, SUM(quantity) AS Measure_Value
FROM gold.fact_sales

UNION ALL

SELECT 
'Avg Price' AS Measures, AVG(price) AS Measure_Value
FROM gold.fact_sales

UNION ALL

SELECT 
'Total Orders' AS Measures, COUNT(DISTINCT order_number) AS Measure_Value
FROM gold.fact_sales

UNION ALL

SELECT
'Total Products' AS Measures, COUNT(product_name) AS Measure_Value
FROM gold.dim_products

UNION ALL

SELECT
'Total Customers' AS Measures ,COUNT(customer_key) AS Measure_Value
FROM gold.dim_customers


----------------------------
--Magnitude Analysis
----------------------------

--Find total customers by countires

SELECT

country,
COUNT(customer_key) AS Total_Customers

FROM gold.dim_customers
GROUP BY country
ORDER BY Total_Customers DESC

--Find Total customers by gender

SELECT

gender,
COUNT(customer_key) AS Total_Customers

FROM gold.dim_customers
GROUP BY gender

--Total Products By Categories

SELECT 
category,
COUNT(DISTINCT product_key) AS Total_Products
FROM gold.dim_products
GROUP BY category
ORDER BY Total_Products DESC

--Average cost in each Category
SELECT 
category,
AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC

--Revenue Generated by each category

SELECT
p.category,
SUM(f.sales_amount) AS Total_Revenue

FROM gold.fact_sales f

LEFT JOIN gold.dim_products p

ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY Total_Revenue DESC

--Find Revenue Generated by each customer

SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS Revenue

FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY Revenue DESC

--Dsitribution of sold item by country

SELECT 
c.country,
SUM(f.quantity) AS Quantity

FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.country
ORDER BY Quantity DESC

-- Total Sales By Country

SELECT 
c.country,
SUM(f.sales_amount) AS Sales

FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY Sales DESC	

-- Total Quantity By Category

SELECT 
p.category,
SUM(f.quantity) AS Quantity
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY Quantity DESC

-- Average Price By Product
SELECT 
p.product_id,
p.product_name,
AVG(f.price) AS Avg_Price 
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY
p.product_id,
p.product_name
ORDER BY Avg_Price DESC

--Total Orders By Customers

SELECT 
c.customer_id,
c.first_name,
c.last_name,
COUNT(f.order_number) AS Total_Orders

FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_id,
c.first_name,
c.last_name
ORDER BY Total_Orders DESC


---------------------------------
--RANKING ANALYSIS
---------------------------------

--5 Products Generated Highest Revenue
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

SELECT *
FROM
(
	SELECT
	p.product_name,
	SUM(f.sales_amount) AS total_revenue,
	ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS Rank_Products
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
	GROUP BY p.product_name
)t
WHERE Rank_Products <=5

--5 Worst Products in terms of Sales

SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue
